#!/bin/bash

# Source function library.
. /etc/init.d/functions

DRCOM_PATH=/usr/local/bin
RETVAL=0

start() {
 	echo -n $"Starting drcomd: "
	$DRCOM_PATH/drcomd
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] || return $RETVAL
	$DRCOM_PATH/drcomc login
	RETVAL=$?
	echo
	return $RETVAL
}	
stop() {
	echo -n $"Shutting down drcomd: "
	$DRCOM_PATH/drcomc logout
	killall drcomd
	RETVAL=$?
	echo
	return $RETVAL
}
restart() {
	stop
	start
}	
reload() {
	stop
	start
}	
case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
	reload
	;;
  condrestart)
  	restart 
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart}"
	exit 1
esac

exit $?

